global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'airflow'
    static_configs:
      - targets: ['airflow-webserver:8080']

  - job_name: 'weather-prediction-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:8000']
    scrape_interval: 5s
